# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/protos/options.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amodel/protos/options.proto\x12\x0cmodel.protos\x1a google/protobuf/descriptor.proto\"\x94\x01\n\x0eMappingOptions\x12\x14\n\x07\x64ivisor\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04unit\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06target\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tconverter\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\n\n\x08_divisorB\x07\n\x05_unitB\t\n\x07_targetB\x0c\n\n_converter::\n\x0cmap_to_homie\x12\x1f.google.protobuf.MessageOptions\x18\xd1\x86\x03 \x01(\x08\x88\x01\x01:Y\n\x0fmapping_options\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x0b\x32\x1c.model.protos.MappingOptions\x88\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model.protos.options_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(map_to_homie)
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(mapping_options)

  DESCRIPTOR._options = None
  _MAPPINGOPTIONS._serialized_start=79
  _MAPPINGOPTIONS._serialized_end=227
# @@protoc_insertion_point(module_scope)
